volumes:
  postgres-data:

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"