services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h ${POSTGRES_HOST} -c 'SELECT 1'|| exit 1"]
      interval: 5s
      timeout: 20s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: migrations/Dockerfile
    environment:
      - DATABASE_URL
    depends_on:
      db:
        condition: service_healthy

  smtp:
    image: rnwood/smtp4dev:v3
    restart: unless-stopped
    ports:
      - ${SMTP_WEB_PORT}:80
      - ${SMTP_PORT}:25
    volumes:
      - smtp4dev-data:/smtp4dev

volumes:
  postgres-data:
  smtp4dev-data:
