services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  smtp:
    image: rnwood/smtp4dev:v3
    restart: unless-stopped
    ports:
      - ${SMTP_WEB_PORT}:80
      - ${SMTP_PORT}:25
    volumes:
      - smtp4dev-data:/smtp4dev

volumes:
  postgres-data:
  smtp4dev-data:
