POST http://localhost:4000/v1/tokens/verification HTTP/1.1
content-type: application/json

{
    "email": "johndoe@gmail"
}

###

POST http://localhost:4000/v1/users HTTP/1.1
content-type: application/json

{
    "email": "johndoe@gmail.com",
    "password": "helloworld",
    "token": "JTAJI4G5WVVJ4T6OM5VTKYXMVE"
}

###

POST http://localhost:4000/v1/tokens/authentication HTTP/1.1
content-type: application/json

{
    "email": "johndoe@gmail.com",
    "password": "helloworld"
}
